# Generated by Django 4.2.10 on 2024-04-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mediassist_app', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_approval',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mediassist_app.cash_request'),
        ),
    ]
